spring:
  datasource:
#    url: jdbc:mysql://@mysqlServer@/@mysqlDB@?characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    username: @mysqlUsername@
#    password: @mysqlPassword@
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: sz2003gd78439851
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
    tomcat:
      max-active: 10


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

  global-config:
    db-config:
      id-type: auto
      column-format: "`%s`"